checks:
    javascript: true
build:
  nodes:
    coverage:
      tests:
        override:
          - command: npm test
    analysis:
            tests:
                override:
                    - js-scrutinizer-run
