language: node_js

node_js:
    - "12"
    - "10"

sudo: false

git:
    submodules: false

dist: xenial
services:
  - xvfb

addons:
  apt:
    sources:
      - google-chrome

before_script:
    - npm install

script:
    - npm test